services:
  next:
    container_name: next_app
    build:
      context: .
      dockerfile: ./infrastructure/docker/Dockerfile
      secrets:
        - github_token
    restart: on-failure
    networks:
      - internal
      - 420cry.test
    ports:
      - "3000:3000"

  nginx:
    container_name: app_web
    image: 420.crypto.test/nginx:next
    depends_on:
      - next
    restart: on-failure
    networks:
      - internal
      - 420cry.test

networks:
  internal:
    name: app_internal
  420cry.test:
    name: 420cry.test
    external: true

secrets:
  github_token:
    environment: GITHUB_TOKEN