import type { Config } from 'tailwindcss'

export default {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './node_modules/@420cry/420cry-lib/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        // Theme-based colors from @420cry/420cry-lib
        primary: {
          DEFAULT: 'var(--theme-primary-500, #0ea5e9)',
          50: 'var(--theme-primary-50, #f0f9ff)',
          100: 'var(--theme-primary-100, #e0f2fe)',
          200: 'var(--theme-primary-200, #bae6fd)',
          300: 'var(--theme-primary-300, #7dd3fc)',
          400: 'var(--theme-primary-400, #38bdf8)',
          500: 'var(--theme-primary-500, #0ea5e9)',
          600: 'var(--theme-primary-600, #0284c7)',
          700: 'var(--theme-primary-700, #0369a1)',
          800: 'var(--theme-primary-800, #075985)',
          900: 'var(--theme-primary-900, #0c4a6e)',
        },
        secondary: {
          DEFAULT: 'var(--theme-secondary-500, #a855f7)',
          50: 'var(--theme-secondary-50, #faf5ff)',
          100: 'var(--theme-secondary-100, #f3e8ff)',
          200: 'var(--theme-secondary-200, #e9d5ff)',
          300: 'var(--theme-secondary-300, #d8b4fe)',
          400: 'var(--theme-secondary-400, #c084fc)',
          500: 'var(--theme-secondary-500, #a855f7)',
          600: 'var(--theme-secondary-600, #9333ea)',
          700: 'var(--theme-secondary-700, #7e22ce)',
          800: 'var(--theme-secondary-800, #6b21a8)',
          900: 'var(--theme-secondary-900, #581c87)',
        },
        success: {
          DEFAULT: 'var(--theme-success-500, #22c55e)',
          50: 'var(--theme-success-50, #f0fdf4)',
          100: 'var(--theme-success-100, #dcfce7)',
          200: 'var(--theme-success-200, #bbf7d0)',
          300: 'var(--theme-success-300, #86efac)',
          400: 'var(--theme-success-400, #4ade80)',
          500: 'var(--theme-success-500, #22c55e)',
          600: 'var(--theme-success-600, #16a34a)',
          700: 'var(--theme-success-700, #15803d)',
          800: 'var(--theme-success-800, #166534)',
          900: 'var(--theme-success-900, #14532d)',
        },
        warning: {
          DEFAULT: 'var(--theme-warning-500, #f59e0b)',
          50: 'var(--theme-warning-50, #fffbeb)',
          100: 'var(--theme-warning-100, #fef3c7)',
          200: 'var(--theme-warning-200, #fde68a)',
          300: 'var(--theme-warning-300, #fcd34d)',
          400: 'var(--theme-warning-400, #fbbf24)',
          500: 'var(--theme-warning-500, #f59e0b)',
          600: 'var(--theme-warning-600, #d97706)',
          700: 'var(--theme-warning-700, #b45309)',
          800: 'var(--theme-warning-800, #92400e)',
          900: 'var(--theme-warning-900, #78350f)',
        },
        danger: {
          DEFAULT: 'var(--theme-danger-500, #ef4444)',
          50: 'var(--theme-danger-50, #fef2f2)',
          100: 'var(--theme-danger-100, #fee2e2)',
          200: 'var(--theme-danger-200, #fecaca)',
          300: 'var(--theme-danger-300, #fca5a5)',
          400: 'var(--theme-danger-400, #f87171)',
          500: 'var(--theme-danger-500, #ef4444)',
          600: 'var(--theme-danger-600, #dc2626)',
          700: 'var(--theme-danger-700, #b91c1c)',
          800: 'var(--theme-danger-800, #991b1b)',
          900: 'var(--theme-danger-900, #7f1d1d)',
        },
        gray: {
          DEFAULT: 'var(--theme-gray-500, #6b7280)',
          50: 'var(--theme-gray-50, #f9fafb)',
          100: 'var(--theme-gray-100, #f3f4f6)',
          200: 'var(--theme-gray-200, #e5e7eb)',
          300: 'var(--theme-gray-300, #d1d5db)',
          400: 'var(--theme-gray-400, #9ca3af)',
          500: 'var(--theme-gray-500, #6b7280)',
          600: 'var(--theme-gray-600, #4b5563)',
          700: 'var(--theme-gray-700, #374151)',
          800: 'var(--theme-gray-800, #1f2937)',
          900: 'var(--theme-gray-900, #111827)',
        },
        neutralDark: '#080B1A',
        'neutralGray-3': '#CFD0D3',
        'neutralGray-5': '#797980',
        // Theme-aware button colors
        'button-default-bg': 'var(--color-button-default-bg)',
        'button-default-text': 'var(--color-button-default-text)',
        'button-default-border': 'var(--color-button-default-border)',
        'button-default-hover': 'var(--color-button-default-hover)',
        'button-default-ring': 'var(--color-button-default-ring)',
        'button-outline-border': 'var(--color-button-outline-border)',
        'button-outline-text': 'var(--color-button-outline-text)',
        'button-outline-hover-bg': 'var(--color-button-outline-hover-bg)',
        'button-outline-hover-text': 'var(--color-button-outline-hover-text)',
        'button-text-text': 'var(--color-button-text-text)',
        'button-text-hover': 'var(--color-button-text-hover)',
        'badge-bg': 'var(--color-badge-bg)',
        'badge-text': 'var(--color-badge-text)',
        'badge-ring': 'var(--color-badge-ring)',
        // Input field colors
        'input-bg': 'var(--color-input-bg)',
        'input-text': 'var(--color-input-text)',
        'input-border': 'var(--color-input-border)',
        'input-placeholder': 'var(--color-input-placeholder)',
        'input-focus-border': 'var(--color-input-focus-border)',
        'input-focus-ring': 'var(--color-input-focus-ring)',
        // Card colors
        'card-border': 'var(--color-card-border)',
        'card-bg-light': 'var(--color-card-bg-light)',
        'card-bg-dark': 'var(--color-card-bg-dark)',
        'card-icon': 'var(--color-card-icon)',
        'card-hover': 'var(--color-card-hover)',
        'card-ring': 'var(--color-card-ring)',
      },
      spacing: {
        // Theme-based spacing
        'theme-xs': 'var(--theme-spacing-xs, 0.25rem)',
        'theme-sm': 'var(--theme-spacing-sm, 0.5rem)',
        'theme-md': 'var(--theme-spacing-md, 1rem)',
        'theme-lg': 'var(--theme-spacing-lg, 1.5rem)',
        'theme-xl': 'var(--theme-spacing-xl, 2rem)',
        'theme-2xl': 'var(--theme-spacing-2xl, 3rem)',
        'theme-3xl': 'var(--theme-spacing-3xl, 4rem)',
      },
      borderRadius: {
        // Theme-based border radius
        'theme-sm': 'var(--theme-radius-sm, 0.125rem)',
        'theme-md': 'var(--theme-radius-md, 0.375rem)',
        'theme-lg': 'var(--theme-radius-lg, 0.5rem)',
        'theme-xl': 'var(--theme-radius-xl, 0.75rem)',
        'theme-2xl': 'var(--theme-radius-2xl, 1rem)',
        'theme-3xl': 'var(--theme-radius-3xl, 1.5rem)',
        'theme-full': 'var(--theme-radius-full, 9999px)',
      },
      boxShadow: {
        // Theme-based shadows
        'theme-sm': 'var(--theme-shadow-sm)',
        'theme-md': 'var(--theme-shadow-md)',
        'theme-lg': 'var(--theme-shadow-lg)',
        'theme-xl': 'var(--theme-shadow-xl)',
        'theme-2xl': 'var(--theme-shadow-2xl)',
      },
    },
  },
  plugins: [],
} satisfies Config
