name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read   # Required for accessing repository contents (read-only)
  pull-requests: write  # Required for write access to pull requests (if applicable)


permissions:
  contents: read   # Required for accessing repository contents (read-only)
  pull-requests: write  # Required for write access to pull requests (if applicable)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies with npm
        run: npm install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Run linting
      - name: Run lint
        run: npm run lint

      # Build the Next.js app
      - name: Build Next.js app
        run: npm run build
