name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Create a custom secret file with the GitHub token
      - name: Create GitHub token file
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" > github_token.txt

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build the Docker image with the Dockerfile in ./infrastructure/docker/Dockerfile
      - name: Build Docker image
        run: |
          docker build \
            --file ./infrastructure/docker/Dockerfile \
            --tag 420cry.test/next:latest \
            --build-arg GITHUB_TOKEN_FILE=github_token.txt \
            .

      # Clean up the token file
      - name: Clean up GitHub token file
        run: rm github_token.txt